name: CI

on:
  push:
    branches:
      - master  
jobs:
  build:
    runs-on: windows-latest  
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.11.0'  # Indica la versión de Node.js que deseas utilizar
    
    - name: Install dependencies
      run: npm install
      
    - name: Build
      run: npm run build  # Cambia "build" por el script de compilación de tu aplicación, si es necesario
